#!/usr/bin/env python3
import sys

def text_to_c_array(name="output"):
    lines = sys.stdin.read().splitlines()
    print(f'char *{name}[] = {{')
    for line in lines:
        escaped_line = line.replace("\\", "\\\\").replace('"', '\\"')
        print(f'    "{escaped_line}",')
    print(f'    NULL')
    print('};')

if __name__ == "__main__":
    name = "output"
    if len(sys.argv) > 1:
        name = sys.argv[1]
    text_to_c_array(name)
